name: Run Ruby Script

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input'
        required: true
        default: 'default_value1'
      input2:
        description: 'Second input'
        required: false
        default: 'default_value2'
  # schedule:
  #   - cron: '*/6 * * * *'

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'  # Specify the Ruby version

    - name: Run Ruby script
      id: script_link
      run: |
        if [ "${{ env.input1 }}" == "default_value1" ]; then
          echo "if part"
          ruby CICDScripts/script.rb
          LINK=$(cat link.txt)
          echo "slink=${{ env.LINK }}" >> $GITHUB_OUTPUT
        else
          echo "else part"
          echo "slink=idk" >> $GITHUB_OUTPUT
        fi

    - name: Access the link environment variable
      env:
        special: ${{ steps.script_link.outputs.slink}}
      run: echo "The link is correct"

