name: Run Ruby Script

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input'
        required: true
        default: 'default_value1'
      input2:
        description: 'Second input'
        required: false
        default: 'default_value2'

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'

    - name: Run Ruby script conditionally
      run: |
        if [ "${{ github.event.inputs.input1 }}" == "default_value1" ]; then
          echo "Running Ruby script to set real links"
          ruby CICDScripts/script.rb
        else
          echo "Setting dummy links"
          echo "group1_PUBLIC_LINK=idk" >> $GITHUB_ENV
          echo "group2_PUBLIC_LINK=idk" >> $GITHUB_ENV
          echo "beta_PUBLIC_LINK=idk" >> $GITHUB_ENV
        fi
        echo "---- Verifying ------"
        echo "group1_PUBLIC_LINK=$group1_PUBLIC_LINK"
        echo "group2_PUBLIC_LINK=$group2_PUBLIC_LINK"
        echo "beta_PUBLIC_LINK=$beta_PUBLIC_LINK"

    - name: Print Environment Variables
      run: |
        echo "---- Verifying Environment Variables ----"
        echo "group1_PUBLIC_LINK=$group1_PUBLIC_LINK"
        echo "group2_PUBLIC_LINK=$group2_PUBLIC_LINK"
        echo "beta_PUBLIC_LINK=$beta_PUBLIC_LINK"
