name: Run Ruby Script

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input'
        required: true
        default: 'default_value1'
      input2:
        description: 'Second input'
        required: false
        default: 'default_value2'

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.x'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Ruby script
      run: |
        ruby CICDScripts/script.rb
      env:
        ENV_VAR1: ${{ github.event.inputs.input1 }}
        ENV_VAR2: ${{ github.event.inputs.input2 }}
        CUSTOM_ENV_VAR1: ${{ secrets.CUSTOM_ENV_VAR1 }}
        CUSTOM_ENV_VAR2: 'another_value'
