name: Push to Release Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of the branch to create and push"
        required: true
        default: "feature2"

jobs:
  push-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set branch name
      id: set-branch-name
      run: |
        echo "RELEASE_BRANCH=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create and Push Release Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout -b ${{ env.RELEASE_BRANCH }}
        git push --set-upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/yeshwanthkhelgi/demo.git ${{ env.RELEASE_BRANCH }}
