name: Release Plan

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the release branch'
        required: true
        default: 'feature2'

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Push remote url to github
      run: |
        url="git@github.com:yeshwanthkhelgi/demo"
        git remote set-url --push origin "$url"
        
    - name: Set branch name
      id: branch-name
      run: echo "release_branch_name=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV

    - name: Create release branch
      run: |
        git checkout -b ${{ env.release_branch_name }}
        echo "Created branch ${{ env.release_branch_name }}"

    - name: Push to release branch
      run: |
        git push --set-upstream origin ${{ env.release_branch_name }}
