name: Push to Release Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of the branch to create and push"
        required: true
        default: "feature2"
        
  # schedule:
  #   - cron: "*/5 * * * *"  # Runs every 5 minutes

env:
  RELEASE_BRANCH: ${{ github.event.inputs.branch_name || 'feature2' }}

jobs:
  push-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Configure Git
    #   run: |
    #     git config --global user.name "GitHub Actions"
    #     git config --global user.email "actions@github.com"

    - name: Create and Push Release Branch
      run: |
        git fetch origin
        if git rev-parse --verify origin/${{ env.RELEASE_BRANCH }} >/dev/null 2>&1; then
          echo "Branch ${{ env.RELEASE_BRANCH }} already exists. Skipping creation."
        else
          git checkout -b ${{ env.RELEASE_BRANCH }}
          git push origin ${{ env.RELEASE_BRANCH }}
        fi

   
